server:
  port: 10000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microweb
    # url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: create

services:
  rest:
    server: http://localhost:10001
    createPath: /tasks
    unapprovedListPath: /tasks?done=false
